title: Tech blog
description: My Personal blog about tech topics
author: Guillaume Beuzeboc
github: https://github.com/Guillaumebeuzeboc
about: Interested in robotics, I am working on software mainly with linux
disqus_shortname: https-guillaumebeuzeboc-github-io
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/BeuzebocG"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/guillaume-beuzeboc/"
    - icon: fa-github
      link: "https://github.com/Guillaumebeuzeboc"

share:
  twitter_username: BeuzebocG

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://guillaumebeuzeboc.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
